Fix junit paths. commented out pytest job for test

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -42,15 +42,15 @@ jobs:
       run: |
         python -m pip install flake8 black bandit mypy lxml pylint 
         python -m pip install pytest pytest-cov pytest-xdist pytest-check aiohttp nbconvert jupyter_contrib_nbextensions Pygments responses
-    - name: Pytest
-      env:
-        MAXMIND_AUTH: ${{ secrets.MAXMIND_AUTH }} 
-        IPSTACK_AUTH: ${{ secrets.IPSTACK_AUTH }}
-        MSTICPYCONFIG: ./tests/msticpyconfig-test.yaml 
-        MSTICPY_TEST_NOSKIP: 1 
-      run: |
-        pytest tests -n auto --junitxml=junit/test-results.xml --cov=msticpy --cov-report=xml
-      if: ${{ success() || failure() }} 
+    #- name: Pytest
+    #  env:
+    #    MAXMIND_AUTH: ${{ secrets.MAXMIND_AUTH }} 
+    #    IPSTACK_AUTH: ${{ secrets.IPSTACK_AUTH }}
+    #    MSTICPYCONFIG: ./tests/msticpyconfig-test.yaml 
+    #    MSTICPY_TEST_NOSKIP: 1 
+    #  run: |
+    #    pytest tests -n auto --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov=msticpy --cov-report=xml
+    #  if: ${{ success() || failure() }} 
     - name: black
       run: |
         black -t py36 --check --exclude venv . "
@@ -70,7 +70,7 @@ jobs:
         prospector --ignore-paths tests --without-tool pylint
     - name: mypy
       run: |
-        mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers --junit-xml junit/mypy-test-results.xml msticpy
+        mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers --junit-xml junit/mypy-test-results-${{ matrix.python-version }}.xml msticpy
     - name: Upload pytest test results
       uses: actions/upload-artifact@v2
       with:
